import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://jjcc:Password$123@us-stage1.jjcustomerconnect.com/store/en/login');
  await page.getByRole('link', { name: 'SiGN UP' }).click();
  await page.locator('label').filter({ hasText: 'Place Order' }).click();
  await page.locator('label').filter({ hasText: 'I am a Johnson & Johnson' }).click();
  await page.getByRole('textbox', { name: 'WWID' }).click();
  await page.getByRole('textbox', { name: 'WWID' }).fill('123');
  await page.getByRole('textbox', { name: 'Supervisor Name' }).click();
  await page.getByRole('textbox', { name: 'Supervisor Name' }).fill('abc');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('7013987465');
  await page.getByRole('textbox', { name: 'Supervisor Email' }).click();
  await page.getByRole('textbox', { name: 'Supervisor Email' }).fill('vu@jnj.com');
  await page.getByRole('button', { name: 'Next Step' }).nth(1).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('ah');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('bv');
  await page.getByRole('textbox', { name: 'Organization Name' }).click();
  await page.getByRole('textbox', { name: 'Organization Name' }).fill('gg');
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('listbox').getByRole('option', { name: 'IT' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('vu@jnj.com');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('701387654');
  await page.getByRole('textbox', { name: 'Company Name' }).click();
  await page.getByRole('textbox', { name: 'Company Name' }).fill('as');
  await page.getByRole('textbox', { name: 'Company Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Company Address' }).click();
  await page.getByRole('textbox', { name: 'Company Name' }).fill('asB');
  await page.getByRole('textbox', { name: 'Company Address' }).fill('AS');
  await page.getByRole('textbox', { name: 'Company Address' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Zip Code' }).click();
  await page.getByRole('textbox', { name: 'Zip Code' }).fill('88776');
  await page.getByRole('button', { name: 'Select Country' }).click();
  await page.getByRole('listbox').getByRole('option', { name: 'USA' }).click();
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).fill('aa');
  await page.getByRole('button', { name: 'Select State' }).click();
  await page.getByRole('listbox').getByRole('option', { name: 'California' }).click();
  await page.getByRole('button', { name: 'Next Step' }).nth(1).click();
  await page.getByRole('button', { name: 'Next Step' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('7013876544');
  await page.getByRole('button', { name: 'Next Step' }).nth(1).click();
  await page.getByRole('button', { name: 'Next Step' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('jjcc1234');
  await page.getByText('Confirm Password* The').click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('jjcc1234');
  await page.getByRole('checkbox', { name: 'I have read and agree to the Terms and Conditions' }).check();
  await page.getByRole('checkbox', { name: 'I have read and agree to the Privacy Policy' }).check();
  await page.getByRole('button', { name: 'Select Security Question' }).first().click();
  await page.getByRole('listbox').getByRole('option', { name: 'What is your pet\'s name?' }).click();
  await page.locator('[id="secretQuestionsAnswers0.answer"]').click();
  await page.locator('[id="secretQuestionsAnswers0.answer"]').click();
  await page.locator('[id="secretQuestionsAnswers0.answer"]').fill('ss');
  await page.getByRole('button', { name: 'Select Security Question' }).first().click();
  await page.getByRole('listbox').getByRole('option', { name: 'What is the name of the hospital where you were born?' }).click();
  await page.locator('[id="secretQuestionsAnswers1.answer"]').click();
  await page.locator('[id="secretQuestionsAnswers1.answer"]').fill('aa');
  await page.getByRole('button', { name: 'Select Security Question' }).click();
  await page.getByRole('listbox').getByRole('option', { name: 'What was your favorite place' }).click();
  await page.locator('[id="secretQuestionsAnswers2.answer"]').click();
  await page.locator('[id="secretQuestionsAnswers2.answer"]').fill('aa');
});