const { chromium } = require('playwright');
const LOGIN_URL = process.env.LOGIN_URL || 'https://jjcc:Password$123@us-stage1.jjcustomerconnect.com/store/en/login';
const USERNAME = process.env.APP_USERNAME || 'vi@jnj.com';
const PASSWORD = process.env.APP_PASSWORD || 'Vivek@7013';
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto(LOGIN_URL, { waitUntil: 'domcontentloaded' });
  await page.fill('#j_username', USERNAME);
  await page.fill('#j_password', PASSWORD);
  await page.press('#j_password', 'Enter');
  await page.waitForURL('**/store/en/**', { timeout: 60000 });
  console.log('logged in', page.url());
  await page.click('xpath=//a[text()="Catalog"]');
  await page.click('xpath=//a[text()="BALVERSA"]');
  await page.click('xpath=(//a[text()="BALVERSA 3MG 84 TBL BOTTLE USA"])[1]');
  await page.locator('xpath=//input[@id="addToCart" and contains(@class, "btnclsactive")]').waitFor({ state: 'visible', timeout: 30000 });
  await page.click('xpath=//input[@id="addToCart" and contains(@class, "btnclsactive")]');
  await page.click('#cart-btn-holder');
  await page.click('xpath=//button[text()="Validate"]');
  console.log('after validate URL', page.url());
  const shippingPageButtons = await page.locator('//button[contains(@class, "shippingPage") or contains(translate(normalize-space(.), "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"), "continue") or contains(translate(normalize-space(.), "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"), "payment")]').allTextContents();
  console.log('shipping-related button texts', shippingPageButtons);
  const allButtons = await page.locator('button').allTextContents();
  console.log('all button texts sample', allButtons.slice(0, 20));
  await page.screenshot({ path: 'debug-shipping.png', fullPage: true });
  await page.click('xpath=(//button[contains(@class,\'shippingPage\')])[1]');
  await page.click('xpath=(//a[text()="CONTINUE TO PAYMENT" or contains(translate(normalize-space(.),\'ABCDEFGHIJKLMNOPQRSTUVWXYZ\' ,\'abcdefghijklmnopqrstuvwxyz\'),\'continue to payment\')])[1]');
  await page.waitForSelector('#purchOrder', { timeout: 30000 });
  const value = await page.getAttribute('#purchOrder', 'value');
  console.log('po field value before', value);
  await page.click('#purchOrder');
  await page.fill('#purchOrder', 't-test');
  await page.press('#purchOrder', 'Tab');
  await page.waitForTimeout(1000);
  const value2 = await page.inputValue('#purchOrder');
  console.log('po field value after', value2);
  const error = await page.locator('text=Please enter the PO Number').count();
  console.log('error count', error);
  const reviewCount = await page.locator('//button[contains(translate(normalize-space(.),\'ABCDEFGHIJKLMNOPQRSTUVWXYZ\',\'abcdefghijklmnopqrstuvwxyz\'),\'continue to review\')]').count();
  console.log('review count', reviewCount);
  await page.click('//button[contains(translate(normalize-space(.),\'ABCDEFGHIJKLMNOPQRSTUVWXYZ\',\'abcdefghijklmnopqrstuvwxyz\'),\'continue to review\')]');
  await page.waitForTimeout(2000);
  const url = page.url();
  console.log('after review url', url);
  const placeOrderCount = await page.locator('//button[contains(translate(normalize-space(.),\'ABCDEFGHIJKLMNOPQRSTUVWXYZ\',\'abcdefghijklmnopqrstuvwxyz\'),\'place order\') or //input[contains(translate(@value,\'ABCDEFGHIJKLMNOPQRSTUVWXYZ\',\'abcdefghijklmnopqrstuvwxyz\'),\'place order\')]').count();
  console.log('place order count', placeOrderCount);
  const bodyText = await page.textContent('body');
  console.log('body contains review:', bodyText && bodyText.includes('Review'));
  await browser.close();
})();
